<?php
declare(strict_types=1); require_once dirname(__DIR__).'/bootstrap.php'; msp2RequireAccess();
$flash=msp2PullFlash();$error=null;$garantias=[];$cuentas=[];$historial=[];
function gdMonto(mixed $v):string{return '$ '.number_format((float)$v,0,',','.');}
try{
 $garantias=$conn->query("SELECT id_garantia,id_contrato_arriendo,nombre_locatario,rut,cdo_local,monto_pactado,monto_recibido,monto_reservado,monto_aplicado,monto_devuelto,monto_disponible FROM dbo.msp_vw_garantias_control_integral WHERE estado_garantia<>6 AND monto_disponible>0 AND monto_reservado=0 ORDER BY nombre_locatario,cdo_local")->fetchAll()?:[];
 $cuentas=$conn->query("SELECT * FROM dbo.msp_vw_tesoreria_saldos WHERE tipo_cuenta IN(N'CAJA',N'BANCO') AND activo=1 ORDER BY tipo_cuenta DESC,banco,nombre_cuenta")->fetchAll()?:[];
 $historial=$conn->query("SELECT TOP(100)d.*,a.nombre_locatario,l.cdo_local,tc.nombre_cuenta,tc.banco banco_origen FROM dbo.msp_garantia_devoluciones d JOIN dbo.msp_garantias g ON g.id_garantia=d.id_garantia JOIN dbo.msp_contratos_arriendo c ON c.id_contrato_arriendo=g.id_contrato_arriendo JOIN dbo.msp_arrendatarios a ON a.id_arrendatario=c.id_arrendatario JOIN dbo.msp_locales l ON l.id_local=g.id_local JOIN dbo.msp_tesoreria_cuentas tc ON tc.id_cuenta_tesoreria=d.id_cuenta_tesoreria ORDER BY d.fecha_devolucion DESC,d.id_devolucion_garantia DESC")->fetchAll()?:[];
}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'No fue posible cargar las devoluciones.';}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Devolución de garantías | MSP</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"><link rel="stylesheet" href="/portalgp/styles.css"><style>
.gd-return-card .card-header{padding:.55rem .8rem}.gd-return-card .card-body{padding:.7rem .8rem .75rem}#formDevolucion{--bs-gutter-y:.55rem;--bs-gutter-x:.75rem}#formDevolucion .form-label{margin-bottom:.2rem;font-size:.84rem;font-weight:600}#formDevolucion .form-control,#formDevolucion .form-select{min-height:36px;padding-top:.34rem;padding-bottom:.34rem;font-size:.88rem}#formDevolucion .form-text{margin-top:.15rem;font-size:.75rem;line-height:1.2}#formDevolucion textarea{min-height:38px;resize:vertical}#gd_resumen .alert{padding:.45rem .6rem}#gd_resumen small{font-size:.7rem}#gd_resumen strong{font-size:.84rem}
</style></head><body class="gp-layout bg-light"><?php include dirname(__DIR__,2).'/templates/header.php';msp2RenderCsrfAutoFieldScript();?><main class="gp-main container-fluid py-3 px-lg-4">
<div class="d-flex justify-content-between gap-2 mb-3"><div><p class="text-muted mb-1">MSP / Garantías</p><h1 class="h3">Devolución de garantía</h1></div><a class="btn btn-outline-dark btn-sm align-self-start" href="<?php echo msp2Escape(msp2Url('garantias/index.php'));?>"><i class="bi bi-arrow-left me-1"></i>Volver a Garantías</a></div>
<?php if(is_array($flash)):?><div class="alert alert-<?php echo msp2Escape((string)($flash['type']??'info'));?>"><?php echo msp2Escape((string)($flash['message']??''));?></div><?php endif;if($error):?><div class="alert alert-danger"><?php echo msp2Escape($error);?></div><?php endif;?>
<div class="card shadow-sm gd-return-card"><div class="card-header fw-semibold">Emitir devolución</div><div class="card-body"><form method="post" action="<?php echo msp2Escape(msp2Url('garantias/registrar_devolucion.php'));?>" class="row g-2" id="formDevolucion"><?php msp2CsrfField();?>
<div class="col-12 col-lg-6"><label class="form-label">Garantía</label><select name="id_garantia" id="gd_garantia" class="form-select" required><option value="">Seleccionar arrendatario y local</option><?php foreach($garantias as $g):?><option value="<?php echo (int)$g['id_garantia'];?>" data-max="<?php echo msp2Escape((string)$g['monto_disponible']);?>" data-pactado="<?php echo msp2Escape((string)$g['monto_pactado']);?>" data-recibido="<?php echo msp2Escape((string)$g['monto_recibido']);?>" data-aplicado="<?php echo msp2Escape((string)$g['monto_aplicado']);?>" data-devuelto="<?php echo msp2Escape((string)$g['monto_devuelto']);?>" data-beneficiario="<?php echo msp2Escape((string)$g['nombre_locatario']);?>" data-rut="<?php echo msp2Escape((string)$g['rut']);?>"><?php echo msp2Escape($g['nombre_locatario'].' · Contrato #'.$g['id_contrato_arriendo'].' · Local '.$g['cdo_local'].' · Disponible '.gdMonto($g['monto_disponible']));?></option><?php endforeach;?></select></div><div class="col-6 col-lg-3"><label class="form-label">Fecha</label><input type="date" name="fecha_devolucion" class="form-control" value="<?php echo date('Y-m-d');?>" required></div><div class="col-6 col-lg-3"><label class="form-label">Monto</label><input type="number" name="monto_devolucion" id="gd_monto" class="form-control" min="0.01" step="0.01" required></div>
<div id="gd_resumen" class="col-12 d-none"><div class="alert alert-info mb-0"><div class="row text-center g-2"><?php foreach(['pactado'=>'Pactada','recibido'=>'Recibida','aplicado'=>'Aplicada a deudas','devuelto'=>'Devuelta antes','disponible'=>'Disponible','posterior'=>'Saldo posterior'] as $id=>$label):?><div class="col-6 col-md"><small><?php echo $label;?></small><strong class="d-block" id="gd_<?php echo $id;?>"></strong></div><?php endforeach;?></div></div></div>
<div class="col-12 col-md-2"><label class="form-label">RUT beneficiario</label><input name="rut_beneficiario" id="gd_rut" maxlength="20" class="form-control"></div><div class="col-12 col-md-4"><label class="form-label">Beneficiario</label><input name="beneficiario" id="gd_beneficiario" maxlength="200" class="form-control" required></div><div class="col-6 col-md-2"><label class="form-label">Medio</label><select name="medio_devolucion" id="gd_medio" class="form-select" required><option value="TRANSFERENCIA">Transferencia</option><option value="EFECTIVO">Efectivo</option></select></div><div class="col-6 col-md-4"><label class="form-label">Cuenta de origen</label><select name="id_cuenta_tesoreria" id="gd_cuenta" class="form-select" required><option value="">Seleccionar</option><?php foreach($cuentas as $c):?><option value="<?php echo (int)$c['id_cuenta_tesoreria'];?>" data-tipo="<?php echo msp2Escape((string)$c['tipo_cuenta']);?>"><?php echo msp2Escape((($c['banco']??'')!==''?$c['banco'].' · ':'').$c['nombre_cuenta'].' · '.gdMonto($c['saldo_actual']));?></option><?php endforeach;?></select><div class="form-text">Transferencia usa banco; efectivo usa caja.</div></div>
<div class="col-12 col-md-3 transferencia"><label class="form-label">Banco destino</label><input name="banco_destino" class="form-control" maxlength="120"></div><div class="col-12 col-md-3 transferencia"><label class="form-label">Cuenta destino</label><input name="cuenta_destino" class="form-control" maxlength="100"></div><div class="col-12 col-md-6 transferencia"><label class="form-label">Referencia transferencia</label><input name="referencia_transferencia" class="form-control" maxlength="200"></div>
<div class="col-12 col-lg-8"><label class="form-label">Motivo y autorización</label><input name="motivo_autorizacion" class="form-control" maxlength="500" placeholder="Indica por qué se devuelve y quién autorizó" required></div><div class="col-12 col-lg-4"><label class="form-label">Observaciones</label><textarea name="observaciones" class="form-control" rows="1" maxlength="500"></textarea></div><div class="col-12 text-end"><button class="btn btn-danger btn-sm" <?php echo $cuentas===[]?'disabled':'';?> onclick="return confirm('¿Confirmas la devolución y el movimiento de tesorería?');">Emitir devolución</button></div></form></div></div>
<div class="card shadow-sm mt-3"><div class="card-header fw-semibold">Historial de devoluciones</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Fecha</th><th>Arrendatario/local</th><th>Medio</th><th>Origen</th><th>Referencia</th><th>Motivo</th><th class="text-end">Monto</th><th>Estado</th></tr></thead><tbody><?php if($historial===[]):?><tr><td colspan="8" class="text-center text-muted py-4">Sin devoluciones.</td></tr><?php endif;foreach($historial as $d):?><tr><td><?php echo msp2Escape(substr((string)$d['fecha_devolucion'],0,10));?></td><td><?php echo msp2Escape((string)$d['nombre_locatario']);?><div class="small text-muted">Local <?php echo msp2Escape((string)$d['cdo_local']);?></div></td><td><?php echo msp2Escape((string)$d['medio_devolucion']);?></td><td><?php echo msp2Escape(trim((string)($d['banco_origen']??'').' · '.$d['nombre_cuenta'],' ·'));?></td><td><?php echo msp2Escape((string)($d['referencia_transferencia']??'-'));?></td><td><?php echo msp2Escape((string)($d['motivo_autorizacion']??$d['observaciones']??'-'));?></td><td class="text-end fw-semibold"><?php echo gdMonto($d['monto_devolucion']);?></td><td><?php echo msp2Escape((string)$d['estado_devolucion']);?></td></tr><?php endforeach;?></tbody></table></div></div>
</main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script><script>(()=>{const g=document.getElementById('gd_garantia'),m=document.getElementById('gd_monto'),medio=document.getElementById('gd_medio'),cuenta=document.getElementById('gd_cuenta'),b=document.getElementById('gd_beneficiario'),r=document.getElementById('gd_rut'),res=document.getElementById('gd_resumen');const money=n=>'$ '+Number(n||0).toLocaleString('es-CL');function posterior(){const o=g.selectedOptions[0];document.getElementById('gd_posterior').textContent=money(Math.max(0,Number(o?.dataset.max||0)-Number(m.value||0)));}function pick(){const o=g.selectedOptions[0];if(!o?.value){res.classList.add('d-none');return;}res.classList.remove('d-none');['pactado','recibido','aplicado','devuelto'].forEach(k=>document.getElementById('gd_'+k).textContent=money(o.dataset[k]));document.getElementById('gd_disponible').textContent=money(o.dataset.max);m.max=o.dataset.max;b.value=o.dataset.beneficiario||'';r.value=o.dataset.rut||'';posterior();}function sync(){const tipo=medio.value==='EFECTIVO'?'CAJA':'BANCO';Array.from(cuenta.options).forEach(o=>{if(!o.value)return;o.hidden=o.dataset.tipo!==tipo;o.disabled=o.hidden;});if(cuenta.selectedOptions[0]?.dataset.tipo!==tipo)cuenta.value='';document.querySelectorAll('.transferencia').forEach(e=>e.classList.toggle('d-none',medio.value!=='TRANSFERENCIA'));}g.addEventListener('change',pick);m.addEventListener('input',posterior);medio.addEventListener('change',sync);sync();})();</script></body></html>
