<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';msp2RequireAccess();$error=null;$rows=[];$tot=[];
$q=msp2NormalizeText((string)($_GET['q']??''));$alerta=strtoupper(trim((string)($_GET['alerta']??'')));$estado=strtoupper(trim((string)($_GET['estado']??'')));$permitidas=['','OK','SIN_MONTO','NO_RECIBIDA','RECEPCION_PARCIAL','RECEPCION_EXCEDIDA','SALDO_RESERVADO','INCONSISTENCIA_SALDO'];if(!in_array($alerta,$permitidas,true))$alerta='';$estados=['','NO_RECIBIDA','PARCIAL','COMPLETA','EXCEDIDA'];if(!in_array($estado,$estados,true))$estado='';
$conditions=['1=1'];$params=[];if($q!==''){$conditions[]="(nombre_locatario LIKE :q OR rut LIKE :q OR nombre_comercial LIKE :q OR cdo_local LIKE :q OR CAST(id_contrato_arriendo AS NVARCHAR(20)) LIKE :q)";$params[':q']='%'.$q.'%';}if($alerta!==''){$conditions[]='alerta_codigo=:alerta';$params[':alerta']=$alerta;}if($estado!==''){$conditions[]='estado_recepcion=:estado';$params[':estado']=$estado;}$where=implode(' AND ',$conditions);
function grMonto(mixed $v):string{return '$ '.number_format((float)$v,2,',','.');}
try{$stmt=$conn->prepare("SELECT COUNT(*) registros,SUM(monto_pactado) pactado,SUM(monto_recibido) recibido,SUM(monto_pendiente_recepcion) pendiente,SUM(monto_disponible) disponible,SUM(monto_reservado) reservado,SUM(monto_aplicado) aplicado,SUM(monto_devuelto) devuelto,SUM(CASE WHEN alerta_nivel>0 THEN 1 ELSE 0 END) alertas FROM dbo.msp_vw_garantias_control_integral WHERE $where");$stmt->execute($params);$tot=$stmt->fetch()?:[];$stmt=$conn->prepare("SELECT * FROM dbo.msp_vw_garantias_control_integral WHERE $where ORDER BY alerta_nivel DESC,nombre_locatario,cdo_local,id_garantia");$stmt->execute($params);$rows=$stmt->fetchAll()?:[];}catch(Throwable $e){$error='No fue posible cargar el reporte integral de garantías.';}
$queryExport=http_build_query(array_filter(['q'=>$q,'alerta'=>$alerta,'estado'=>$estado],fn($v)=>$v!==''));
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Control de garantías | MSP</title><link rel="stylesheet" href="/portalgp/assets/vendor/bootstrap-5.3.0/css/bootstrap.min.css"><link rel="stylesheet" href="/portalgp/assets/vendor/bootstrap-icons-1.11.3/font/bootstrap-icons.css"><link rel="stylesheet" href="/portalgp/styles.css"></head><body class="gp-layout bg-light"><?php include dirname(__DIR__,2).'/templates/header.php';?><main class="gp-main container-fluid py-3 px-lg-4 msp-guarantees-report"><div class="d-flex flex-wrap justify-content-between align-items-start gap-2 mb-3" data-gp-commandbar><div><p class="text-muted mb-1">MSP / Garantías</p><h1 class="h3 mb-1">Control integral de garantías</h1><p class="text-muted mb-0">Monto pactado, recepción, disponibilidad, reservas, aplicaciones y devoluciones.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-secondary btn-sm" href="<?php echo msp2Escape(msp2Url('garantias/index.php'));?>"><i class="bi bi-arrow-left me-1"></i>Volver a Garantías</a><a class="btn btn-primary btn-sm" href="<?php echo msp2Escape(msp2Url('garantias/exportar_reporte.php'.($queryExport!==''?'?'.$queryExport:'')));?>"><i class="bi bi-file-earmark-spreadsheet me-1"></i>Exportar CSV</a></div></div><?php if($error):?><div class="alert alert-danger"><?php echo msp2Escape($error);?></div><?php endif;?>
<form method="get" class="card card-body mb-3"><div class="row g-2 align-items-end"><div class="col-lg-5"><label class="form-label">Buscar</label><input name="q" value="<?php echo msp2Escape($q);?>" class="form-control" placeholder="Arrendatario, RUT, tienda, contrato o local"></div><div class="col-lg-3"><label class="form-label">Alerta</label><select name="alerta" class="form-select"><option value="">Todas</option><?php foreach(array_slice($permitidas,1) as $a):?><option value="<?php echo $a;?>" <?php echo $alerta===$a?'selected':'';?>><?php echo msp2Escape(str_replace('_',' ',$a));?></option><?php endforeach;?></select></div><div class="col-lg-2"><label class="form-label">Recepción</label><select name="estado" class="form-select"><option value="">Todas</option><?php foreach(array_slice($estados,1) as $e):?><option value="<?php echo $e;?>" <?php echo $estado===$e?'selected':'';?>><?php echo msp2Escape(str_replace('_',' ',$e));?></option><?php endforeach;?></select></div><div class="col-lg-2 d-grid"><button class="btn btn-primary">Filtrar</button></div></div></form>
<section class="gp-indicator-strip mb-3" aria-label="Resumen integral de garantías"><?php foreach(['Pactado'=>'pactado','Recibido'=>'recibido','Pendiente recepción'=>'pendiente','Disponible'=>'disponible','Reservado'=>'reservado','Aplicado'=>'aplicado','Devuelto'=>'devuelto'] as $label=>$key):?><div class="gp-indicator"><span class="gp-indicator-label"><?php echo msp2Escape($label);?></span><strong class="gp-indicator-value<?php echo $key==='disponible'?' text-success':'';?>"><?php echo msp2Escape(grMonto($tot[$key]??0));?></strong></div><?php endforeach;?><div class="gp-indicator"><span class="gp-indicator-label">Alertas</span><strong class="gp-indicator-value text-warning-emphasis"><?php echo (int)($tot['alertas']??0);?> / <?php echo (int)($tot['registros']??0);?></strong></div></section>
<div class="msp-guarantees-table-wrap gp-table-shell">
    <table class="table table-hover table-sm align-middle mb-0 msp-guarantees-table gp-table-compact gp-table-mobile-cards">
        <thead class="table-light"><tr><th>Arrendatario / local</th><th data-gp-column-kind="short">Contrato</th><th>Recepción</th><th>Saldo de garantía</th><th>Egresos</th><th>Alerta</th><th data-gp-column-kind="actions">Acciones</th></tr></thead>
        <tbody>
        <?php if($rows===[]):?><tr class="gp-table-empty-row"><td colspan="7" class="gp-table-empty-cell">Sin resultados.</td></tr><?php endif;?>
        <?php foreach($rows as $r):$level=(int)$r['alerta_nivel'];$badge=$level>=3?'danger':($level===2?'warning':($level===1?'secondary':'success'));?>
            <tr>
                <td data-gp-label="Arrendatario / local"><div class="fw-semibold"><?php echo msp2Escape((string)$r['nombre_locatario']);?></div><div class="small text-muted"><?php echo msp2Escape((string)$r['rut']);?></div><div class="small text-muted"><?php echo msp2Escape((string)$r['nombre_comercial']);?> · Local <?php echo msp2Escape((string)$r['cdo_local']);?></div></td>
                <td data-gp-label="Contrato" class="text-center"><strong>#<?php echo (int)$r['id_contrato_arriendo'];?></strong><div class="small text-muted">Garantía <?php echo (int)$r['id_garantia'];?></div></td>
                <td data-gp-label="Recepción"><span class="gp-data-pair"><span>Pactado</span><strong><?php echo msp2Escape(grMonto($r['monto_pactado']));?></strong></span><span class="gp-data-pair"><span>Recibido</span><strong><?php echo msp2Escape(grMonto($r['monto_recibido']));?></strong></span><span class="gp-data-pair"><span>Pendiente</span><strong><?php echo msp2Escape(grMonto($r['monto_pendiente_recepcion']));?></strong></span></td>
                <td data-gp-label="Saldo de garantía"><span class="gp-data-pair gp-data-pair--total"><span>Disponible</span><strong><?php echo msp2Escape(grMonto($r['monto_disponible']));?></strong></span><span class="gp-data-pair"><span>Reservado</span><strong><?php echo msp2Escape(grMonto($r['monto_reservado']));?></strong></span></td>
                <td data-gp-label="Egresos"><span class="gp-data-pair"><span>Aplicado</span><strong><?php echo msp2Escape(grMonto($r['monto_aplicado']));?></strong></span><span class="gp-data-pair"><span>Devuelto</span><strong><?php echo msp2Escape(grMonto($r['monto_devuelto']));?></strong></span></td>
                <td data-gp-label="Alerta"><span class="badge text-bg-<?php echo $badge;?>" title="<?php echo msp2Escape(str_replace('_',' ',(string)$r['alerta_codigo']));?>"><?php echo msp2Escape(str_replace('_',' ',(string)$r['alerta_codigo']));?></span><div class="small text-muted mt-1 cell-ellipsis" title="<?php echo msp2Escape((string)$r['alerta_descripcion']);?>"><?php echo msp2Escape((string)$r['alerta_descripcion']);?></div></td>
                <td data-gp-label="Acciones" class="gp-cell-actions"><div class="msp-guarantees-actions"><a class="btn btn-outline-success btn-sm" href="<?php echo msp2Escape(msp2Url('garantias/recepciones.php?id_garantia='.(int)$r['id_garantia']));?>" title="Recepciones" aria-label="Recepciones"><i class="bi bi-box-arrow-in-down"></i></a><a class="btn btn-outline-danger btn-sm" href="<?php echo msp2Escape(msp2Url('garantias/devoluciones.php?id_garantia='.(int)$r['id_garantia']));?>" title="Devoluciones" aria-label="Devoluciones"><i class="bi bi-box-arrow-up"></i></a><a class="btn btn-outline-secondary btn-sm" href="<?php echo msp2Escape(msp2Url('contratos/ficha.php?id_contrato_arriendo='.(int)$r['id_contrato_arriendo']));?>" title="Ficha del contrato" aria-label="Ficha del contrato"><i class="bi bi-file-earmark-text"></i></a></div></td>
            </tr>
        <?php endforeach;?>
        </tbody>
    </table>
</div></main><?php require_once dirname(__DIR__, 2) . '/templates/components/page_navigation.php'; ?><script<?= function_exists('pgpCspNonceAttribute') ? pgpCspNonceAttribute() : '' ?> src="/portalgp/assets/vendor/bootstrap-5.3.0/js/bootstrap.bundle.min.js"></script></body></html>
