<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit;
}

$root = dirname(__DIR__);
$allowlistPath = $root . '/config/csp_inline_attribute_hashes.php';
$applyNonces = in_array('--apply-nonces', $argv, true);
$writeAllowlist = in_array('--write-allowlist', $argv, true);
$excludedPrefixes = ['vendor/', 'tests/', 'scripts/'];
$nonceSnippet = "<?= function_exists('pgpCspNonceAttribute') ? pgpCspNonceAttribute() : '' ?>";
$hashes = ['script' => [], 'style' => []];
$filesChanged = 0;
$tagsChanged = 0;
$missingNonceTags = [];

/**
 * @return list<int>
 */
function pgpCspTemplateMissingNonceLines(string $source): array
{
    $tokens = token_get_all($source);
    $missing = [];
    foreach ($tokens as $index => $token) {
        if (!is_array($token) || $token[0] !== T_INLINE_HTML) {
            continue;
        }
        if (preg_match_all('~<(?:script|style)\\b~i', $token[1], $matches, PREG_OFFSET_CAPTURE) === false) {
            continue;
        }
        foreach ($matches[0] ?? [] as $match) {
            $tagText = (string) $match[0];
            $offset = (int) $match[1];
            $tail = substr($token[1], $offset + strlen($tagText));
            if (preg_match('~^[^>]*\\bnonce\\s*=~i', $tail) === 1) {
                continue;
            }
            if (strpos($tail, '>') === false) {
                $phpFragment = '';
                for ($lookahead = $index + 1; $lookahead < count($tokens); $lookahead++) {
                    $next = $tokens[$lookahead];
                    $phpFragment .= is_array($next) ? $next[1] : $next;
                    if (is_array($next) && $next[0] === T_CLOSE_TAG) {
                        break;
                    }
                }
                if (str_contains($phpFragment, 'pgpCspNonceAttribute')) {
                    continue;
                }
            }
            $missing[] = $token[2] + substr_count(substr($token[1], 0, $offset), "\n");
        }
    }
    return $missing;
}

$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator($root, FilesystemIterator::SKIP_DOTS)
);

foreach ($iterator as $file) {
    if (!$file->isFile() || strtolower($file->getExtension()) !== 'php') {
        continue;
    }
    $path = $file->getPathname();
    $relative = str_replace('\\', '/', substr($path, strlen($root) + 1));
    foreach ($excludedPrefixes as $prefix) {
        if (str_starts_with($relative, $prefix)) {
            continue 2;
        }
    }

    $source = file_get_contents($path);
    if (!is_string($source)) {
        throw new RuntimeException('No se pudo leer ' . $relative);
    }
    $tokens = token_get_all($source);
    $rebuilt = '';
    $fileChanged = false;
    foreach ($tokens as $token) {
        if (!is_array($token)) {
            $rebuilt .= $token;
            continue;
        }
        $text = $token[1];
        if ($token[0] === T_INLINE_HTML) {
            if ($applyNonces) {
                $replaced = preg_replace_callback(
                    '~<(script|style)\\b(?![^>]*\\bnonce\\s*=)~i',
                    static function (array $match) use ($nonceSnippet, &$tagsChanged): string {
                        $tagsChanged++;
                        return '<' . $match[1] . $nonceSnippet;
                    },
                    $text
                );
                if (is_string($replaced) && $replaced !== $text) {
                    $text = $replaced;
                    $fileChanged = true;
                }
            }

            foreach ([
                'script' => '~\\son[a-z][a-z0-9_-]*\\s*=\\s*(["\'])(.*?)\\1~is',
                'style' => '~\\sstyle\\s*=\\s*(["\'])(.*?)\\1~is',
            ] as $kind => $pattern) {
                if (preg_match_all($pattern, $text, $matches) === false) {
                    continue;
                }
                foreach ($matches[2] ?? [] as $rawValue) {
                    $value = html_entity_decode((string) $rawValue, ENT_QUOTES | ENT_HTML5, 'UTF-8');
                    $hashes[$kind][base64_encode(hash('sha256', $value, true))] = true;
                }
            }
        }
        $rebuilt .= $text;
    }

    if ($fileChanged) {
        if (file_put_contents($path, $rebuilt) === false) {
            throw new RuntimeException('No se pudo actualizar ' . $relative);
        }
        $filesChanged++;
    }
    foreach (pgpCspTemplateMissingNonceLines($rebuilt) as $line) {
        $missingNonceTags[] = $relative . ':' . $line;
    }
}

foreach ($hashes as &$items) {
    $items = array_keys($items);
    sort($items, SORT_STRING);
}
unset($items);

$export = "<?php\n"
    . "declare(strict_types=1);\n\n"
    . "// Generated by scripts/csp_templates.php from trusted PHP templates.\n"
    . "return " . var_export($hashes, true) . ";\n";

if ($writeAllowlist) {
    if (file_put_contents($allowlistPath, $export) === false) {
        throw new RuntimeException('No se pudo escribir la lista CSP.');
    }
} elseif (!is_file($allowlistPath) || file_get_contents($allowlistPath) !== $export) {
    fwrite(STDERR, "La lista CSP no coincide. Ejecuta --write-allowlist.\n");
    exit(1);
}

echo json_encode([
    'files_changed' => $filesChanged,
    'tags_changed' => $tagsChanged,
    'script_attribute_hashes' => count($hashes['script']),
    'style_attribute_hashes' => count($hashes['style']),
    'allowlist_written' => $writeAllowlist,
    'missing_nonce_tags' => count($missingNonceTags),
], JSON_UNESCAPED_SLASHES), PHP_EOL;

if ($missingNonceTags !== []) {
    fwrite(STDERR, "Etiquetas script/style sin nonce en plantilla:\n");
    fwrite(STDERR, implode("\n", $missingNonceTags) . "\n");
    exit(1);
}
