<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/bootstrap.php';
msp2RequireAccess();
$flash=msp2PullFlash();$error=null;$cuentas=[];$cajas=[];$bancos=[];$movimientos=[];$depositos=[];
$fecha=trim((string)($_GET['fecha']??date('Y-m-d')));$date=DateTimeImmutable::createFromFormat('!Y-m-d',$fecha);if(!$date||$date->format('Y-m-d')!==$fecha)$fecha=date('Y-m-d');
function tdMonto(mixed $v):string{return '$ '.number_format((float)$v,2,',','.');}
try{
    foreach(['msp_tesoreria_cuentas','msp_tesoreria_movimientos','msp_tesoreria_depositos','msp_vw_tesoreria_saldos'] as $t)if(!msp2TableExists($conn,$t))throw new RuntimeException('Falta instalar msp/db/patch_tesoreria_depositos.sql.');
    $cuentas=$conn->query("SELECT * FROM dbo.msp_vw_tesoreria_saldos WHERE activo=1 ORDER BY CASE tipo_cuenta WHEN N'CAJA' THEN 0 ELSE 1 END,nombre_cuenta")->fetchAll()?:[];
    foreach($cuentas as $c){if(($c['tipo_cuenta']??'')==='CAJA')$cajas[]=$c;else $bancos[]=$c;}
    $stmt=$conn->prepare("SELECT m.*,c.nombre_cuenta,c.tipo_cuenta,c.banco FROM dbo.msp_tesoreria_movimientos m JOIN dbo.msp_tesoreria_cuentas c ON c.id_cuenta_tesoreria=m.id_cuenta_tesoreria WHERE m.fecha_movimiento=:fecha ORDER BY m.fecha_registro DESC,m.id_movimiento_tesoreria DESC");$stmt->execute([':fecha'=>$fecha]);$movimientos=$stmt->fetchAll()?:[];
    $stmt=$conn->prepare("SELECT d.*,cc.nombre_cuenta caja,cb.nombre_cuenta cuenta_banco,cb.banco FROM dbo.msp_tesoreria_depositos d JOIN dbo.msp_tesoreria_cuentas cc ON cc.id_cuenta_tesoreria=d.id_cuenta_caja JOIN dbo.msp_tesoreria_cuentas cb ON cb.id_cuenta_tesoreria=d.id_cuenta_banco WHERE d.fecha_deposito=:fecha ORDER BY d.id_deposito_tesoreria DESC");$stmt->execute([':fecha'=>$fecha]);$depositos=$stmt->fetchAll()?:[];
}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'No fue posible cargar tesorería.';}
$entradaDia=0.0;$salidaDia=0.0;foreach($movimientos as $m){if(($m['estado_movimiento']??'')!=='VIGENTE')continue;if(($m['naturaleza']??'')==='E')$entradaDia+=(float)$m['monto'];else $salidaDia+=(float)$m['monto'];}
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tesorería diaria | MSP</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"><link rel="stylesheet" href="/portalgp/styles.css"><style>
.td-main .card-header{padding:.55rem .75rem}.td-main .card-body{padding:.7rem .8rem}.td-main .form-label{margin-bottom:.2rem;font-size:.84rem;font-weight:600}.td-main .form-control,.td-main .form-select{min-height:36px;padding-top:.34rem;padding-bottom:.34rem;font-size:.88rem}.td-main .table>:not(caption)>*>*{padding:.45rem .55rem}.td-control-summary{padding:.65rem .8rem}.td-control-summary-inner{display:flex;align-items:flex-end;justify-content:space-between;gap:.8rem;flex-wrap:wrap}.td-date-form{display:flex;align-items:flex-end;gap:.5rem;flex-wrap:wrap}.td-date-field{min-width:210px}.td-day-metrics{display:flex;align-items:stretch;justify-content:flex-end;gap:.35rem;flex-wrap:wrap}.td-day-metric{min-width:145px;padding:.3rem .6rem;border-left:3px solid #d9e2ec;background:#f7f9fc;border-radius:.35rem}.td-day-metric small{display:block;color:#65758b;font-size:.72rem}.td-day-metric strong{display:block;font-size:.95rem;line-height:1.35}.td-day-metric--in{border-left-color:#198754}.td-day-metric--out{border-left-color:#dc3545}.td-day-metric--net{border-left-color:#0d6efd}.td-deposit-card form{--bs-gutter-y:.55rem}.td-deposit-card textarea{min-height:38px;resize:vertical}@media(max-width:767.98px){.td-date-form,.td-day-metrics{width:100%}.td-date-field{flex:1;min-width:170px}.td-day-metric{flex:1;min-width:105px}}
</style></head>
<body class="gp-layout bg-light"><?php include dirname(__DIR__,2).'/templates/header.php';msp2RenderCsrfAutoFieldScript(); ?><main class="gp-main container-fluid py-3 px-lg-4 td-main">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><p class="text-muted mb-1">MSP / Tesorería</p><h1 class="h3 mb-0">Control diario de caja y bancos</h1></div><div class="d-flex flex-wrap gap-2"><a class="btn btn-outline-dark btn-sm" href="<?php echo msp2Escape(msp2Url('garantias/index.php')); ?>"><i class="bi bi-arrow-left me-1"></i>Volver a Garantías</a><a class="btn btn-outline-success btn-sm" href="<?php echo msp2Escape(msp2Url('tesoreria/conciliacion.php')); ?>">Conciliar / cerrar caja</a></div></div>
<?php if(is_array($flash)):?><div class="alert alert-<?php echo msp2Escape((string)($flash['type']??'info')); ?>"><?php echo msp2Escape((string)($flash['message']??'')); ?></div><?php endif;if($error):?><div class="alert alert-danger"><?php echo msp2Escape($error); ?></div><?php endif;?>
<div class="card td-control-summary mb-3"><div class="td-control-summary-inner"><form method="get" class="td-date-form"><div class="td-date-field"><label class="form-label">Fecha de control</label><input type="date" name="fecha" class="form-control" value="<?php echo msp2Escape($fecha); ?>"></div><button class="btn btn-primary">Consultar</button></form><div class="td-day-metrics"><div class="td-day-metric td-day-metric--in"><small>Entradas del día</small><strong class="text-success"><?php echo msp2Escape(tdMonto($entradaDia)); ?></strong></div><div class="td-day-metric td-day-metric--out"><small>Salidas del día</small><strong class="text-danger"><?php echo msp2Escape(tdMonto($salidaDia)); ?></strong></div><div class="td-day-metric td-day-metric--net"><small>Flujo neto del día</small><strong><?php echo msp2Escape(tdMonto($entradaDia-$salidaDia)); ?></strong></div></div></div></div>
<div class="row g-3"><div class="col-xl-7"><div class="card shadow-sm h-100"><div class="card-header fw-semibold">Saldos actuales</div><div class="table-responsive"><table class="table align-middle mb-0"><thead class="table-light"><tr><th>Cuenta</th><th>Tipo</th><th>Último movimiento</th><th class="text-end">Saldo</th></tr></thead><tbody><?php foreach($cuentas as $c):?><tr><td><div class="fw-semibold"><?php echo msp2Escape((string)$c['nombre_cuenta']);?></div><div class="small text-muted"><?php echo msp2Escape(trim((string)($c['banco']??'').' '.(string)($c['numero_cuenta']??'')));?></div></td><td><span class="badge text-bg-<?php echo $c['tipo_cuenta']==='CAJA'?'warning':'primary';?>"><?php echo msp2Escape((string)$c['tipo_cuenta']);?></span></td><td><?php echo msp2Escape(substr((string)($c['ultima_fecha_movimiento']??'-'),0,10));?></td><td class="text-end fw-semibold"><?php echo msp2Escape(tdMonto($c['saldo_actual']));?></td></tr><?php endforeach;?></tbody></table></div></div></div>
<div class="col-xl-5"><div class="card shadow-sm td-deposit-card"><div class="card-header fw-semibold">Depositar efectivo en banco</div><div class="card-body"><form method="post" action="<?php echo msp2Escape(msp2Url('tesoreria/registrar_deposito.php'));?>" class="row g-2"><?php msp2CsrfField();?><div class="col-md-6"><label class="form-label">Caja origen</label><select name="id_cuenta_caja" class="form-select" required><option value="">Seleccionar</option><?php foreach($cajas as $c):?><option value="<?php echo (int)$c['id_cuenta_tesoreria'];?>"><?php echo msp2Escape($c['nombre_cuenta'].' · '.tdMonto($c['saldo_actual']));?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Banco destino</label><select name="id_cuenta_banco" class="form-select" required><option value="">Seleccionar</option><?php foreach($bancos as $c):?><option value="<?php echo (int)$c['id_cuenta_tesoreria'];?>"><?php echo msp2Escape(($c['banco']??'').' · '.$c['nombre_cuenta']);?></option><?php endforeach;?></select><?php if($bancos===[]):?><div class="form-text text-danger">No hay cuentas bancarias configuradas.</div><?php endif;?></div><div class="col-md-6"><label class="form-label">Fecha</label><input type="date" name="fecha_deposito" class="form-control" value="<?php echo msp2Escape($fecha);?>" required></div><div class="col-md-6"><label class="form-label">Monto</label><input type="number" name="monto_deposito" class="form-control" min="0.01" step="0.01" required></div><div class="col-12"><label class="form-label">N.º comprobante / referencia</label><input name="referencia_deposito" class="form-control" maxlength="200" required></div><div class="col-12"><label class="form-label">Observaciones</label><textarea name="observaciones" class="form-control" rows="1" maxlength="500"></textarea></div><div class="col-12 text-end"><button class="btn btn-success" <?php echo $bancos===[]?'disabled':'';?>>Registrar depósito</button></div></form></div></div></div></div>
<div class="card shadow-sm mt-4"><div class="card-header fw-semibold">Movimientos del <?php echo msp2Escape((new DateTimeImmutable($fecha))->format('d-m-Y'));?></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Cuenta</th><th>Operación</th><th>Medio</th><th>Referencia</th><th class="text-end">Entrada</th><th class="text-end">Salida</th><th>Estado</th></tr></thead><tbody><?php if($movimientos===[]):?><tr><td colspan="7" class="text-center text-muted py-4">Sin movimientos para esta fecha.</td></tr><?php endif;foreach($movimientos as $m):?><tr><td><?php echo msp2Escape((string)$m['nombre_cuenta']);?></td><td><?php echo msp2Escape(str_replace('_',' ',(string)$m['tipo_movimiento']));?></td><td><?php echo msp2Escape((string)$m['medio_pago']);?></td><td><?php echo msp2Escape((string)($m['referencia']??'-'));?></td><td class="text-end text-success"><?php echo $m['naturaleza']==='E'?msp2Escape(tdMonto($m['monto'])):'-';?></td><td class="text-end text-danger"><?php echo $m['naturaleza']==='S'?msp2Escape(tdMonto($m['monto'])):'-';?></td><td><?php echo msp2Escape((string)$m['estado_movimiento']);?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($depositos!==[]):?><div class="card shadow-sm mt-4"><div class="card-header fw-semibold">Depósitos del día</div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>#</th><th>Caja</th><th>Banco</th><th>Referencia</th><th class="text-end">Monto</th><th>Estado</th></tr></thead><tbody><?php foreach($depositos as $d):?><tr><td><?php echo (int)$d['id_deposito_tesoreria'];?></td><td><?php echo msp2Escape((string)$d['caja']);?></td><td><?php echo msp2Escape(($d['banco']??'').' · '.$d['cuenta_banco']);?></td><td><?php echo msp2Escape((string)$d['referencia_deposito']);?></td><td class="text-end"><?php echo msp2Escape(tdMonto($d['monto_deposito']));?></td><td><?php echo msp2Escape((string)$d['estado_deposito']);?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
<div class="card shadow-sm mt-4"><div class="card-header fw-semibold">Agregar cuenta bancaria</div><div class="card-body"><form method="post" action="<?php echo msp2Escape(msp2Url('garantias/guardar_cuenta_banco.php')); ?>" class="row g-2 align-items-end"><?php msp2CsrfField(); ?><div class="col-12 col-md-4"><label class="form-label">Nombre interno</label><input name="nombre_cuenta" class="form-control" maxlength="150" placeholder="Cuenta corriente principal" required></div><div class="col-12 col-md-3"><label class="form-label">Banco</label><input name="banco" class="form-control" maxlength="120" required></div><div class="col-12 col-md-3"><label class="form-label">Número de cuenta</label><input name="numero_cuenta" class="form-control" maxlength="80" required></div><div class="col-12 col-md-2 d-grid"><button class="btn btn-outline-primary">Guardar cuenta</button></div></form></div></div>
</main><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script></body></html>
