<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';msp2RequireAccess();
if(($_SERVER['REQUEST_METHOD']??'GET')!=='POST')msp2Redirect('tesoreria/conciliacion.php');
$cuenta=filter_input(INPUT_POST,'id_cuenta_tesoreria',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);$desde=trim((string)($_POST['fecha_desde']??''));$hasta=trim((string)($_POST['fecha_hasta']??''));[$ok,$saldo]=msp2NormalizeDecimalInput((string)($_POST['saldo_cartola']??''),2);$obs=msp2NormalizeText((string)($_POST['observaciones']??''));$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['movimientos']??[])),fn($v)=>$v>0)));
$d1=DateTimeImmutable::createFromFormat('!Y-m-d',$desde);$d2=DateTimeImmutable::createFromFormat('!Y-m-d',$hasta);
if(!$cuenta||!$ok||$saldo===null||!$d1||!$d2||$d1->format('Y-m-d')!==$desde||$d2->format('Y-m-d')!==$hasta||$desde>$hasta||mb_strlen($obs)>500){msp2SetFlash('warning','Completa correctamente los datos de conciliación.');msp2Redirect('tesoreria/conciliacion.php');}
try{$stmt=$conn->prepare('EXEC dbo.msp_tesoreria_conciliar_banco @id_cuenta_tesoreria=:cuenta,@fecha_desde=:desde,@fecha_hasta=:hasta,@saldo_cartola=:saldo,@movimientos_json=:movimientos,@observaciones=:observaciones,@id_usuario=:usuario');$stmt->execute([':cuenta'=>(int)$cuenta,':desde'=>$desde,':hasta'=>$hasta,':saldo'=>$saldo,':movimientos'=>json_encode($ids,JSON_THROW_ON_ERROR),':observaciones'=>$obs!==''?$obs:null,':usuario'=>(int)$_SESSION['usuario']['id']]);$r=$stmt->fetch()?:[];$estado=(string)($r['estado_conciliacion']??'PENDIENTE');msp2SetFlash($estado==='CUADRADA'?'success':'warning','Conciliación #'.(int)($r['id_conciliacion_tesoreria']??0).' guardada: '.$estado.'. Diferencia: $ '.number_format((float)($r['diferencia']??0),2,',','.').'.');}catch(Throwable $e){msp2SetFlash($e instanceof RuntimeException?'warning':'danger',$e instanceof RuntimeException?$e->getMessage():'No fue posible guardar la conciliación.');}
msp2Redirect('tesoreria/conciliacion.php?cuenta='.(int)$cuenta.'&desde='.rawurlencode($desde).'&hasta='.rawurlencode($hasta));
