<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/bootstrap.php';
msp2RequireAccess();
$flash=msp2PullFlash();$error=null;$cierres=[];$usuarios=[];
try{
 $cierres=$conn->query("SELECT TOP(100)c.*,t.nombre_cuenta FROM dbo.msp_tesoreria_cierres_caja c JOIN dbo.msp_tesoreria_cuentas t ON t.id_cuenta_tesoreria=c.id_cuenta_tesoreria WHERE c.estado_cierre IN(N'CUADRADO',N'CON_DIFERENCIA') ORDER BY c.fecha_cierre DESC,c.id_cierre_caja DESC")->fetchAll()?:[];
 $usuarios=$conn->query("SELECT id,nombre_completo,UserName FROM dbo.cr_usuarios WHERE estado_id=1 ORDER BY nombre_completo,UserName")->fetchAll()?:[];
}catch(Throwable $e){$error='No fue posible cargar los cierres disponibles.';}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reapertura de caja | MSP</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"><link rel="stylesheet" href="/portalgp/styles.css"></head><body class="gp-layout bg-light"><?php include dirname(__DIR__,2).'/templates/header.php';?><main class="gp-main container py-4"><div class="d-flex justify-content-between mb-3"><div><p class="text-muted mb-1">MSP / Tesorería</p><h1 class="h3">Reapertura autorizada de caja</h1><p class="text-muted">Requiere motivo, solicitante autenticado y autorizador habilitado. Todas las reaperturas quedan auditadas.</p></div><a class="btn btn-outline-secondary btn-sm" href="<?php echo msp2Escape(msp2Url('tesoreria/conciliacion.php'));?>">Volver a conciliación</a></div><?php if(is_array($flash)):?><div class="alert alert-<?php echo msp2Escape((string)($flash['type']??'info'));?>"><?php echo msp2Escape((string)($flash['message']??''));?></div><?php endif;if($error):?><div class="alert alert-danger"><?php echo msp2Escape($error);?></div><?php endif;?><div class="card shadow-sm"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Fecha</th><th>Caja</th><th>Estado</th><th>Diferencia</th><th style="min-width:460px">Autorización</th></tr></thead><tbody><?php if($cierres===[]):?><tr><td colspan="5" class="text-center text-muted p-4">No hay cierres activos para reabrir.</td></tr><?php endif;foreach($cierres as $c):?><tr><td><?php echo msp2Escape(substr((string)$c['fecha_cierre'],0,10));?></td><td><?php echo msp2Escape((string)$c['nombre_cuenta']);?></td><td><?php echo msp2Escape((string)$c['estado_cierre']);?></td><td><?php echo '$ '.number_format((float)$c['diferencia'],2,',','.');?></td><td><form method="post" action="<?php echo msp2Escape(msp2Url('tesoreria/reabrir_caja.php'));?>" class="row g-2"><input type="hidden" name="id_cierre_caja" value="<?php echo (int)$c['id_cierre_caja'];?>"><input type="hidden" name="fecha_caja" value="<?php echo msp2Escape(substr((string)$c['fecha_cierre'],0,10));?>"><?php msp2CsrfField();?><div class="col-4"><select name="id_usuario_autoriza" class="form-select form-select-sm" required><option value="">Autorizador</option><?php foreach($usuarios as $u):?><option value="<?php echo (int)$u['id'];?>"><?php echo msp2Escape((string)($u['nombre_completo']?:$u['UserName']));?></option><?php endforeach;?></select></div><div class="col-6"><input name="motivo" class="form-control form-control-sm" minlength="10" maxlength="1000" placeholder="Motivo obligatorio" required></div><div class="col-2 d-grid"><button class="btn btn-sm btn-outline-danger">Reabrir</button></div></form></td></tr><?php endforeach;?></tbody></table></div></div></main><?php include dirname(__DIR__,2).'/templates/footer.php';?></body></html>
